# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformCLI@2
  name: version
  inputs:
    command: 'version'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  name: init
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Pay-As-You-Go(51f12368-372d-48c6-8e3c-02c940c4a791)'
    allowTelemetryCollection: true

- task: TerraformCLI@2
  name: validate
  inputs:
    command: 'validate'
    
- task: TerraformCLI@2
  name: Plan
  inputs:
    command: 'plan'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

